# Generated by Django 4.2.14 on 2024-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images/')),
                ('photo_details', models.TextField(max_length=1000)),
            ],
        ),
    ]
